# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_ui_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(306, 342)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_cargar_entrada = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cargar_entrada.setObjectName("btn_cargar_entrada")
        self.verticalLayout.addWidget(self.btn_cargar_entrada)
        self.lbl_entrada = QtWidgets.QLabel(self.centralwidget)
        self.lbl_entrada.setObjectName("lbl_entrada")
        self.verticalLayout.addWidget(self.lbl_entrada)
        self.btn_cargar_salida = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cargar_salida.setObjectName("btn_cargar_salida")
        self.verticalLayout.addWidget(self.btn_cargar_salida)
        self.lbl_salida = QtWidgets.QLabel(self.centralwidget)
        self.lbl_salida.setObjectName("lbl_salida")
        self.verticalLayout.addWidget(self.lbl_salida)
        self.btn_ejecutar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ejecutar.setObjectName("btn_ejecutar")
        self.verticalLayout.addWidget(self.btn_ejecutar)
        self.ERA5_procesamiento_exportar = QtWidgets.QPushButton(self.centralwidget)
        self.ERA5_procesamiento_exportar.setObjectName("ERA5_procesamiento_exportar")
        self.verticalLayout.addWidget(self.ERA5_procesamiento_exportar)
        self.txt_log = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_log.setObjectName("txt_log")
        self.verticalLayout.addWidget(self.txt_log)
        self.btn_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.verticalLayout.addWidget(self.btn_cancelar)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 306, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SWAT+ IGP: Módulo hidroclimático/Procesamiento NetCDF de ERA5"))
        self.btn_cargar_entrada.setText(_translate("MainWindow", "Cargar carpeta de entrada"))
        self.lbl_entrada.setText(_translate("MainWindow", "Carpeta seleccionada:"))
        self.btn_cargar_salida.setText(_translate("MainWindow", "Seleccionar carpeta de salida"))
        self.lbl_salida.setText(_translate("MainWindow", "Carpeta de salida:"))
        self.btn_ejecutar.setText(_translate("MainWindow", "Ejecutar procesamiento"))
        self.ERA5_procesamiento_exportar.setText(_translate("MainWindow", "Migrar data para el solver SWAT+ MoSSARD"))
        self.txt_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Log del procesamiento</span></p></body></html>"))
        self.btn_cancelar.setText(_translate("MainWindow", "Cancelar procesamiento"))
